# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/arctic_circle
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App
server.port=8081
spring.application.name=arctic-circle-backend

jwt.secret=${JWT_SECRET}
jwt.expiry=${JWT_EXPIRY}

admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
